import type { Metadata } from 'next';
import localfont from 'next/font/local';
import './globals.css';

const neueMontrealRegular = localfont({
  src: [
    { path: '../public/fonts/NeueMontreal-Regular.otf', weight: '400' },
    { path: '../public/fonts/NeueMontreal-Medium.otf', weight: '500' }
  ],
  variable: '--neue-montreal'
});
export const metadata: Metadata = {
  title: 'Kitt Frontend Assignment',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neueMontrealRegular.variable} treal antialiased`}>
        {children}
      </body>
    </html>
  );
}
